refactor: update stack with component-rollup-config
ovh-ux/ovh-angular-contracts pull request #6
Opened 2018-11-22 12:56 UTC by cbourgois

## update stack with [component-rollup-config](https://github.com/ovh-ux/component-rollup-config)

### Description of the Change

488fd24 - refactor: update stack with component-rollup-config

/cc @jleveugle @frenautvh @antleblanc

2018-11-22 12:58 UTC, frenautvh commented on package.json
> +  "main": "./dist/cjs/ovh-angular-contracts.js",
add browser entry with umd

2018-11-22 19:03 UTC, antleblanc requested changes
Nice job but in order to merge this pull request, I give you some comments about things that have to be done.

In fact, we are also aware that you've deleted the `docs` folder which is probably useful for some people that used to `$ grunt:ngdocs`.

Edit:
Missing `.huskyrc.json` file too.

2018-11-22 19:03 UTC, antleblanc commented on .babelrc
> +    "@babel/plugin-syntax-dynamic-import"
I'm not sure that it is useful. I was not able to find any dynamic import from this dependency.

2018-11-22 19:03 UTC, antleblanc commented on .eslintignore
> +dist
According to the `package.json` file, it seems that you only run `eslint` commands through the `src` directory.

ref: https://github.com/ovh-ux/ovh-angular-contracts/pull/6/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R18

For my point of view, this file could be removed.

2018-11-22 19:03 UTC, antleblanc commented on .gitignore
> +dist
Could you please add `tools` due to our internal process?

2018-11-22 19:03 UTC, antleblanc commented on .htmlhintrc
> +{
Pay attention that this configuration is probably not yet the same across all current stack (meaning web/dedicated/cloud and telecom).

We have to tend to an unified HTMLHint configuration.

2018-11-22 19:03 UTC, antleblanc commented on README.md
> +### Yarn
That will be great if we can expose the same skeleton/structure as the newest repository we've created.

Here is what I have in mind:

```txt

# Header 1

> A short description for the dependency

[badges]

## Install

## Usage

## Related

## Contributing

## License
```

2018-11-22 19:03 UTC, antleblanc commented on package.json
> +    "angular"
Could you please provide some keywords?

2018-11-22 19:03 UTC, antleblanc commented on package.json
> +    "lint:js": "eslint --quiet --fix ./src",
```suggestion
    "lint:js": "eslint --quiet --fix src",
```

2018-11-22 19:03 UTC, antleblanc commented on src/ovh-angular-contracts.directive.js
> +      /* eslint-disable no-param-reassign */
For my point of view, I think this is not a good solution to turn off ESLint `no-param-reassign` rule to the entire `link` method.

We have to put some effort to fix as much as we can theses kind of errors.

2018-11-22 19:03 UTC, antleblanc commented on src/ovh-angular-contracts.js
> +const moduleName = 'ovh-angular-contracts';
According to [some recent stuff](https://github.com/ovh-ux/telecom-universe-components/blob/master/src/index.js#L39) that we tackle, it seems that we decided to use the [`camelCase`](https://lodash.com/docs/4.17.10#camelCase) instead of [`kebabCase`](https://lodash.com/docs/4.17.10#kebabCase).

2018-11-23 12:41 UTC, cbourgois commented on src/ovh-angular-contracts.js
> +const moduleName = 'ovh-angular-contracts';
Should we change the angular module name (from `ovh-angular-contracts` to `ovhAngularContracts`) ? It will impact all projects using this module.

2018-11-23 12:51 UTC, cbourgois commented on .eslintignore
> +dist
file removed

2018-11-23 12:51 UTC, cbourgois commented on .gitignore
> +dist
added 👍

2018-11-23 12:52 UTC, cbourgois commented on .htmlhintrc
> +{
Updated with [ovh-manager-web::.htmlhintrc](https://github.com/ovh-ux/telecom-universe-components/blob/master/.htmlhintrc) content

2018-11-23 12:53 UTC, cbourgois commented on package.json
> +    "angular"
+ contracts
+ ovh

2018-11-23 12:53 UTC, cbourgois commented on package.json
> +    "lint:js": "eslint --quiet --fix ./src",
Done

2018-11-23 12:54 UTC, antleblanc commented on src/ovh-angular-contracts.js
> +const moduleName = 'ovh-angular-contracts';
In fact, it make sense if we release a breaking change nor publish this package to the `@ovh-ux` scope.

2018-11-23 12:57 UTC, cbourgois commented
IMO, docs were generated with grunt from the project sources. Sources have changed and we don't have (yet) solution to generate them.
Keeping existing docs have no sense, but we may find a new way to provide documentation.

2018-11-24 09:34 UTC, antleblanc commented on src/ovh-angular-contracts.js
> +const moduleName = 'ovh-angular-contracts';
As you are introducing the `component-rollup-config`, by definition you will introduce a breaking change to the dist folder structure.

From `master` branch:

```sh
$ ls -l dist/
total 40
-rw-r--r--  1 aleblanc  staff  8929 Aug  2 17:47 ovh-angular-contracts.js
-rw-r--r--  1 aleblanc  staff  5447 Nov 24 10:29 ovh-angular-contracts.min.js
```

From `v3.x.x` branch:

```sh
$ ls -l dist/
total 0
drwxr-xr-x  6 aleblanc  staff  192 Nov 24 10:31 cjs
drwxr-xr-x  4 aleblanc  staff  128 Nov 24 10:31 umd
```

2018-11-29 08:42 UTC, cbourgois commented on src/ovh-angular-contracts.directive.js
> +      /* eslint-disable no-param-reassign */
Done.

2018-12-07 09:00 UTC, jleveugle commented
Hello @cbourgois,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

2018-12-20 09:00 UTC, jleveugle commented
Hello @cbourgois,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

2019-01-01 09:00 UTC, jleveugle commented
Hello @cbourgois,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

2019-01-01 09:00 UTC, closed without merging